### ISSUE TITLE
Todo List for 1.0.1

### ISSUE THREAD

**Issue by danggai** [danggai/FindMyPackage#1]
- [x] 메인 화면 > 택배 현재 위치 표기되도록 수정

**Comment by danggai** [comment]
추가
- [ ] 설정 > 사용 된 오픈 소스 확인 가능하도록 수정
- [ ] 설정 > 깃 허브 원본 소스 주소로 연결되는 버튼 추가

**Comment by danggai** [comment]
추가
- [x] 메인 화면 택배 목록 리스트 역순으로 정렬되도록 수정

**Comment by danggai** [comment]
- [x] 택배 상세 보기 > 간헐적으로 리스트 중단이 보이는 문제 수정
- [x] 택배 상세 보기 > 현재 택배 progress에 택배 아이콘 표시되도록 수정

**Comment by danggai** [comment]
- [x] 택배 상세 보기 > 빈 List 수신 시 대응
